---
abstract: 'Use Win32 synchronization objects'
author:
  - 'Christopher J. Madsen <perl@cjmweb.net>'
build_requires:
  ExtUtils::CBuilder: 0.15
  ExtUtils::ParseXS: 0
  File::Spec: 0
  FindBin: 0
  Module::Build: 0.21
  Test::More: 0.88
configure_requires:
  Module::Build: 0.21
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Win32-IPC
no_index:
  directory:
    - tools
requires:
  XSLoader: 0
  perl: 5.006
resources:
  repository: git://github.com/madsen/win32-ipc.git
version: 1.08
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::VersionFromModule
      name: '@CJM/VersionFromModule'
      version: 0.08
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@CJM/GatherDir'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@CJM/PruneCruft'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@CJM/ManifestSkip'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@CJM/MetaJSON'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@CJM/MetaYAML'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::License
      name: '@CJM/License'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@CJM/PodSyntaxTests'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@CJM/PodCoverageTests'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@CJM/ExtraTests'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::PodLoom
      config:
        Pod::Loom version: 0.04
      name: '@CJM/PodLoom'
      version: 3.02
    -
      class: Dist::Zilla::Plugin::ModuleBuild::Custom
      name: '@CJM/ModuleBuild::Custom'
      version: 3.01
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@CJM/MetaConfig'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::MatchManifest
      name: '@CJM/MatchManifest'
      version: 4.00
    -
      class: Dist::Zilla::Plugin::GitVersionCheckCJM
      name: '@CJM/GitVersionCheckCJM'
      version: 3.02
    -
      class: Dist::Zilla::Plugin::TemplateCJM
      name: '@CJM/TemplateCJM'
      version: 3.00
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@CJM/Repository'
      version: 0.16
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@CJM/@Git/Check'
      version: 1.102810
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@CJM/@Git/Commit'
      version: 1.102810
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@CJM/@Git/Tag'
      version: 1.102810
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@CJM/@Git/Push'
      version: 1.102810
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@CJM/TestRelease'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@CJM/UploadToCPAN'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: '@CJM/ArchiveRelease'
      version: 3.01
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: build
          type: requires
      name: BuildRequires
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: 1.101550
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.102345
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.102345
